apiVersion: batch/v1
kind: Job
metadata:
  name: prisma-migrate
  namespace: opspilot
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: ranajitu/opspilot-backend:v1
          command: ["npx", "prisma", "migrate", "deploy"]
          envFrom:
            - secretRef:
                name: opspilot-secrets
  backoffLimit: 3