apiVersion: v1
kind: Secret
metadata:
  name: opspilot-secrets
  namespace: opspilot
type: Opaque
stringData:
  POSTGRES_USER: "opspilot"
  POSTGRES_PASSWORD: "change_me_strong"
  POSTGRES_DB: "OpsPilot"
  REDIS_PASSWORD: "change_me_redis"
  DATABASE_URL: "postgresql://postgres.nixyhxhxwubopnylcstv:5omHOU0UkAwaHTM3@aws-0-ap-northeast-1.pooler.supabase.com:6543/postgres"
  REDIS_URL: "redis://:change_me_redis@redis:6379"
  JWT_ACCESS_SECRET: "replace_with_long_hex"
  JWT_REFRESH_SECRET: "replace_with_long_hex"
  GOOGLE_CLIENT_ID: "1095432013196-n9i7mvj9jofd74ee1oe2fsu7carco9dh.apps.googleusercontent.com"
  OPENAI_API_KEY: "k-proj-Ohl6I8ldOlydJmr3EAM66Q1uICbXP1amP_2aq9A8cQCl6BPtPwT4qCyRUl3yUNff2-o_xHCPjET3BlbkFJGafv70DBI6uI0PhJGn7s_pPpNVglZp5LGuFEkEwGTRssGR_0mbHUPNOvj60C4iLmVfhhddBMMA"
  CLOUDINARY_CLOUD_NAME: "dfb4o9hed"
  CLOUDINARY_API_KEY: "884513698241327"
  CLOUDINARY_API_SECRET: "3cjDGFCjmR4RZFwGbbgXY8mEf2o"
  CLOUDINARY_FOLDER: "opspilot/incidents"